name = "giftflow"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "giftflow"
database_name = "giftflow"
database_id = "914e3f49-bc46-4458-bd8d-00faea64e354" # This will be filled after creation or used locally
migrations_dir = "migrations"
